### ISSUE TITLE
JLCPCB 20mm wide version showing up as 19.78mm wide in the JLCPCB ordering form.

### ISSUE THREAD

**Issue by Aleblazer** [customMK/Bonsai-C#1]
Uploading the JLCPCB 20mm gerbers to the JLCPCB ordering page is showing the width at 19.78mm, this is preventing selection of SMT services.
![SMT2](https://user-images.githubusercontent.com/60912320/136813097-b272f33f-6d6f-43fe-be70-010ac6388064.png)
![SMT Assembly](https://user-images.githubusercontent.com/60912320/136813103-52df281f-0888-4c15-81de-1e34621d2eb7.png)
.

**Comment by infinityis** [comment]
Width has been corrected to 20mm. Also changed the 20mm width to be on the bottom half so that the main section width is normal in case the bottom half is unused and removed manually.
